spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driverClassName: org.postgresql.Driver
    username: postgres
    password: test123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-message: always

